In [16]:
import numpy as np

str1 = '9'
str2 = '5,1,3,6,8,2,9,0,10'

def main(s1, s2):
    len = int(str1)
    m = np.array([int(i) for i in s2.split(",")])
    m1 = np.zeros(len, int)
    m2 = np.zeros(len, int)
    m3 = np.zeros(len, int)
    m4 = np.zeros(len, int)
    m5 = np.zeros(len, int)
    m6 = np.zeros(len, int)
    
    
    m1 = np.argsort(m)
        
    for i in range(len):
        m2[i] = i
    
    for i in range(len):
        m3[m1[i]] = m3[m1[i]] + i
    
    for i in range(len):
        m4[i] = m2[i] + m3[i]

    ind = list(m4).index(min(m4))
    for i in range(len):
        if i < ind:
            m5[i] = 1
        
        if i == ind:
            m5[i] = 0
            mm = m4[i]
        
        if i > ind:
            if m4[i] > mm:
                m5[i] = 0
                mm = m4[i]
            else:
                m5[i] = 1
           
    ind = list(m4).index(max(m4))
    for i in range(len-1, -1, -1):
        
    
    
    print(m)
    print(m1)
    print(m2)
    print(m3)
    print(m4)
    print(m5)
    print(m6)
    print(ind)
    
    
    #for i in range(len):
    #    print(m[m1[i]])

main(str1, str2)

8
7
6
5
4
3
2
1
0
[ 5  1  3  6  8  2  9  0 10]
[7 1 5 2 0 3 4 6 8]
[0 1 2 3 4 5 6 7 8]
[4 1 3 5 6 2 7 0 8]
[ 4  2  5  8 10  7 13  7 16]
[1 0 0 0 0 1 0 1 0]
[0 1 1 0 0 0 0 1 1]
8
